/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "tasks_explorer.h"


void
task_explorer_prog_1(host)
char *host;
{
	CLIENT *clnt;
	int  *result_1;
	char*  task_explorer_init_1_arg;
	int  *result_2;
	char*  task_explorer_free_1_arg;
	host_info_dynamic  *result_3;
	char*  task_explorer_update_1_arg;
	tasks_list  *result_4;
	char*  task_explorer_tasks_list_1_arg;
	task_info_base  *result_5;
	int  task_explorer_base_info_1_arg;
	command_line  *result_6;
	int  task_explorer_params_1_arg;
	int  *result_7;
	int  kill_process_1_arg;
	env_list  *result_8;
	int  task_explorer_env_list_1_arg;
	task_info_dynamic  *result_9;
	int  task_explorer_dyninfo_1_arg;
	files_list  *result_10;
	int  task_explorer_files_list_1_arg;
	app_descr  *result_11;
	int  task_explorer_app_descr_1_arg;
	thread_info_list  *result_12;
	int  task_explorer_threads_info_1_arg;
	stack_info_list  *result_13;
	struct call_stack_request  task_explorer_stack_for_thread_1_arg;
	clnt = clnt_create(host, TASK_EXPLORER_PROG, TASK_EXPLORER, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror(host);
		exit(1);
	}
	result_1 = task_explorer_init_1((void*)&task_explorer_init_1_arg, clnt);
	if (result_1 == NULL) {
		clnt_perror(clnt, "call failed:");
	}
	result_2 = task_explorer_free_1((void*)&task_explorer_free_1_arg, clnt);
	if (result_2 == NULL) {
		clnt_perror(clnt, "call failed:");
	}
	result_3 = task_explorer_update_1((void*)&task_explorer_update_1_arg, clnt);
	if (result_3 == NULL) {
		clnt_perror(clnt, "call failed:");
	}
	result_4 = task_explorer_tasks_list_1((void*)&task_explorer_tasks_list_1_arg, clnt);
	if (result_4 == NULL) {
		clnt_perror(clnt, "call failed:");
	}
	result_5 = task_explorer_base_info_1(&task_explorer_base_info_1_arg, clnt);
	if (result_5 == NULL) {
		clnt_perror(clnt, "call failed:");
	}
	result_6 = task_explorer_params_1(&task_explorer_params_1_arg, clnt);
	if (result_6 == NULL) {
		clnt_perror(clnt, "call failed:");
	}
	result_7 = kill_process_1(&kill_process_1_arg, clnt);
	if (result_7 == NULL) {
		clnt_perror(clnt, "call failed:");
	}
	result_8 = task_explorer_env_list_1(&task_explorer_env_list_1_arg, clnt);
	if (result_8 == NULL) {
		clnt_perror(clnt, "call failed:");
	}
	result_9 = task_explorer_dyninfo_1(&task_explorer_dyninfo_1_arg, clnt);
	if (result_9 == NULL) {
		clnt_perror(clnt, "call failed:");
	}
	result_10 = task_explorer_files_list_1(&task_explorer_files_list_1_arg, clnt);
	if (result_10 == NULL) {
		clnt_perror(clnt, "call failed:");
	}
	result_11 = task_explorer_app_descr_1(&task_explorer_app_descr_1_arg, clnt);
	if (result_11 == NULL) {
		clnt_perror(clnt, "call failed:");
	}
	result_12 = task_explorer_threads_info_1(&task_explorer_threads_info_1_arg, clnt);
	if (result_12 == NULL) {
		clnt_perror(clnt, "call failed:");
	}
	result_13 = task_explorer_stack_for_thread_1(&task_explorer_stack_for_thread_1_arg, clnt);
	if (result_13 == NULL) {
		clnt_perror(clnt, "call failed:");
	}
	clnt_destroy( clnt );
}


main(argc, argv)
int argc;
char *argv[];
{
	char *host;

	if(argc < 2) {
		printf("usage: %s server_host\n", argv[0]);
		exit(1);
	}
	host = argv[1];
	task_explorer_prog_1( host );
}
