/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "tasks_explorer.h"
#include <sys/ioctl.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <netdb.h>
#include <signal.h>
#include <sys/ttycom.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <syslog.h>

#ifdef __STDC__
#define SIG_PF void(*)(int)
#endif

#ifdef DEBUG
#define RPC_SVC_FG
#endif

#define _RPCSVC_CLOSEDOWN 120
static int _rpcpmstart;		/* Started by a port monitor ? */
static int _rpcfdtype;		/* Whether Stream or Datagram ? */
static int _rpcsvcdirty;	/* Still serving ? */

static
void _msgout(msg)
	char *msg;
{
#ifdef RPC_SVC_FG
	if (_rpcpmstart)
		syslog(LOG_ERR, msg);
	else
		(void) fprintf(stderr, "%s\n", msg);
#else
	syslog(LOG_ERR, msg);
#endif
}

static void
closedown()
{
	if (_rpcsvcdirty == 0) {
		extern fd_set svc_fdset;
		static int size;
		int i, openfd;

		if (_rpcfdtype == SOCK_DGRAM)
			exit(0);
		if (size == 0) {
			size = getdtablesize();
		}
		for (i = 0, openfd = 0; i < size && openfd < 2; i++)
			if (FD_ISSET(i, &svc_fdset))
				openfd++;
		if (openfd <= (_rpcpmstart?0:1))
			exit(0);
	}
	(void) alarm(_RPCSVC_CLOSEDOWN);
}

static void
task_explorer_prog_1(rqstp, transp)
	struct svc_req *rqstp;
	SVCXPRT *transp;
{
	union {
		int task_explorer_base_info_1_arg;
		int task_explorer_params_1_arg;
		int kill_process_1_arg;
		int task_explorer_env_list_1_arg;
		int task_explorer_dyninfo_1_arg;
		int task_explorer_files_list_1_arg;
		int task_explorer_app_descr_1_arg;
		int task_explorer_threads_info_1_arg;
		struct call_stack_request task_explorer_stack_for_thread_1_arg;
	} argument;
	char *result;
	bool_t (*xdr_argument)(), (*xdr_result)();
	char *(*local)();

	_rpcsvcdirty = 1;
	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply(transp, (xdrproc_t) xdr_void, (char *)NULL);
		_rpcsvcdirty = 0;
		return;

	case TASK_EXPLORER_INIT:
		xdr_argument = xdr_void;
		xdr_result = xdr_int;
		local = (char *(*)()) task_explorer_init_1_svc;
		break;

	case TASK_EXPLORER_FREE:
		xdr_argument = xdr_void;
		xdr_result = xdr_int;
		local = (char *(*)()) task_explorer_free_1_svc;
		break;

	case TASK_EXPLORER_UPDATE:
		xdr_argument = xdr_void;
		xdr_result = xdr_host_info_dynamic;
		local = (char *(*)()) task_explorer_update_1_svc;
		break;

	case TASK_EXPLORER_TASKS_LIST:
		xdr_argument = xdr_void;
		xdr_result = xdr_tasks_list;
		local = (char *(*)()) task_explorer_tasks_list_1_svc;
		break;

	case TASK_EXPLORER_BASE_INFO:
		xdr_argument = xdr_int;
		xdr_result = xdr_task_info_base;
		local = (char *(*)()) task_explorer_base_info_1_svc;
		break;

	case TASK_EXPLORER_PARAMS:
		xdr_argument = xdr_int;
		xdr_result = xdr_command_line;
		local = (char *(*)()) task_explorer_params_1_svc;
		break;

	case KILL_PROCESS:
		xdr_argument = xdr_int;
		xdr_result = xdr_int;
		local = (char *(*)()) kill_process_1_svc;
		break;

	case TASK_EXPLORER_ENV_LIST:
		xdr_argument = xdr_int;
		xdr_result = xdr_env_list;
		local = (char *(*)()) task_explorer_env_list_1_svc;
		break;

	case TASK_EXPLORER_DYNINFO:
		xdr_argument = xdr_int;
		xdr_result = xdr_task_info_dynamic;
		local = (char *(*)()) task_explorer_dyninfo_1_svc;
		break;

	case TASK_EXPLORER_FILES_LIST:
		xdr_argument = xdr_int;
		xdr_result = xdr_files_list;
		local = (char *(*)()) task_explorer_files_list_1_svc;
		break;

	case TASK_EXPLORER_APP_DESCR:
		xdr_argument = xdr_int;
		xdr_result = xdr_app_descr;
		local = (char *(*)()) task_explorer_app_descr_1_svc;
		break;

	case TASK_EXPLORER_THREADS_INFO:
		xdr_argument = xdr_int;
		xdr_result = xdr_thread_info_list;
		local = (char *(*)()) task_explorer_threads_info_1_svc;
		break;

	case TASK_EXPLORER_STACK_FOR_THREAD:
		xdr_argument = xdr_call_stack_request;
		xdr_result = xdr_stack_info_list;
		local = (char *(*)()) task_explorer_stack_for_thread_1_svc;
		break;

	default:
		svcerr_noproc(transp);
		_rpcsvcdirty = 0;
		return;
	}
	(void) memset((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs(transp, xdr_argument, (caddr_t) &argument)) {
		svcerr_decode(transp);
		_rpcsvcdirty = 0;
		return;
	}
	result = (*local)(&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) xdr_result, result)) {
		svcerr_systemerr(transp);
	}
	if (!svc_freeargs(transp, xdr_argument, (caddr_t) &argument)) {
		_msgout("unable to free arguments");
		exit(1);
	}
	_rpcsvcdirty = 0;
	return;
}



int
main(argc, argv)
int argc;
char *argv[];
{
	SVCXPRT *transp = NULL;
	int sock;
	int proto = 0;
	struct sockaddr_in saddr;
	int asize = sizeof (saddr);

	if (getsockname(0, (struct sockaddr *)&saddr, &asize) == 0) {
		int ssize = sizeof (int);

		if (saddr.sin_family != AF_INET)
			exit(1);
		if (getsockopt(0, SOL_SOCKET, SO_TYPE,
				(char *)&_rpcfdtype, &ssize) == -1)
			exit(1);
		sock = 0;
		_rpcpmstart = 1;
		proto = 0;
		openlog("tasks_explorer", LOG_PID, LOG_DAEMON);
	} else {
#ifndef RPC_SVC_FG
		int size;
		int pid, i;

		pid = fork();
		if (pid < 0) {
			perror("cannot fork");
			exit(1);
		}
		if (pid)
			exit(0);
		size = getdtablesize();
		for (i = 0; i < size; i++)
			(void) close(i);
		i = open("/dev/console", 2);
		(void) dup2(i, 1);
		(void) dup2(i, 2);
		i = open("/dev/tty", 2);
		if (i >= 0) {
			(void) ioctl(i, TIOCNOTTY, (char *)NULL);
			(void) close(i);
		}
		openlog("tasks_explorer", LOG_PID, LOG_DAEMON);
#endif
		sock = RPC_ANYSOCK;
		(void) pmap_unset(TASK_EXPLORER_PROG, TASK_EXPLORER);
	}

	if ((_rpcfdtype == 0) || (_rpcfdtype == SOCK_DGRAM)) {
		transp = svcudp_create(sock);
		if (transp == NULL) {
			_msgout("cannot create udp service.");
			exit(1);
		}
		if (!_rpcpmstart)
			proto = IPPROTO_UDP;
		if (!svc_register(transp, TASK_EXPLORER_PROG, TASK_EXPLORER, task_explorer_prog_1, proto)) {
			_msgout("unable to register (TASK_EXPLORER_PROG, TASK_EXPLORER, udp).");
			exit(1);
		}
	}

	if ((_rpcfdtype == 0) || (_rpcfdtype == SOCK_STREAM)) {
		if (_rpcpmstart)
			transp = svcfd_create(sock, 0, 0);
		else
			transp = svctcp_create(sock, 0, 0);
		if (transp == NULL) {
			_msgout("cannot create tcp service.");
			exit(1);
		}
		if (!_rpcpmstart)
			proto = IPPROTO_TCP;
		if (!svc_register(transp, TASK_EXPLORER_PROG, TASK_EXPLORER, task_explorer_prog_1, proto)) {
			_msgout("unable to register (TASK_EXPLORER_PROG, TASK_EXPLORER, tcp).");
			exit(1);
		}
	}

	if (transp == (SVCXPRT *)NULL) {
		_msgout("could not create a handle");
		exit(1);
	}
	if (_rpcpmstart) {
		(void) signal(SIGALRM, (void(*)()) closedown);
		(void) alarm(_RPCSVC_CLOSEDOWN);
	}
	svc_run();
	_msgout("svc_run returned");
	exit(1);
	/* NOTREACHED */
}
